buildVariable: true
category:
- SERIF
familyName: Noto Serif Bengali
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifBengali.glyphspackage
